# control
remote_controller:
  type: joystick
  available_mode: all

# keyboard:
#   type: joystick
#   available_mode: all

# sensors
septentrio:
  type: gps
  available_mode: all
xsens:
  type: imu
  available_mode: all
mrs1000:
  type: lidar
  available_mode: none

# implements
cultivator:
  type: implement
  available_mode: none
