#!/usr/bin/env python3
import numpy as np
import click


@click.command()
@click.option("-w", "--bed-width", default=4.0, type=float, help="Width of the bed.")
@click.option("-l", "--bed-length", default=45.0, type=float, help="Length of the bed.")
@click.option("-c", "--lines-count", default=6, type=int, help="Number of lines to generate.")
@click.option(
    "--enter-extra-length", default=1.2, type=float, help="Extra length entering the bed."
)
@click.option(
    "-o",
    "--output",
    default="out.csv",
    type=click.Path(writable=True),
    help="Output CSV file name.",
)
def main(bed_width, bed_length, lines_count, enter_extra_length, output):
    """Generate path coordinates and write them to a CSV file."""
    length = bed_length + enter_extra_length
    first_point = np.array([-enter_extra_length, bed_width / 2])
    points = [first_point, np.array([bed_length, first_point[1]])]

    for i in range(lines_count - 1):
        end_x = length if i & 1 else -length
        begin_x = -enter_extra_length if i & 1 else enter_extra_length
        points.append(points[-1] + np.array([begin_x, bed_width]))
        points.append(points[-1] + np.array([end_x, 0.0]))

    points[0][0] += -5.
    points[-1][0] += 5.

    # points.append(points[0])
    # points.append(points[1])

    with open(output, "w") as f:
        f.write("x,y\n")
        for p in points:
            f.write(f"{p[0]},{p[1]}\n")


if __name__ == "__main__":
    main()
