name: "lidar"
launch:
  # - include:
  #     file: "$(find-pkg-share romea_lidar_meta_bringup)/profile/sick_scan_xd_mrs1xxx.launch.py"
  #     arg:
  #       - name: ip
  #         value: "192.168.1.112"
  #       - name: port
  #         value: "2112"
  - include:
      file: $(find-pkg-share romea_lidar_meta_bringup)/profile/gz_bridge.launch.py
      if: $(eval "'$(var mode)' == 'simulation_gazebo'")
configuration:
  manufacturer: sick
  model: mrs
  version: 1000
  rate: 50
  resolution: 0.5
location:
  parent_link: "base_link"
  xyz: [0.88, 0.0, 0.8635]
  rpy: [0.0, 15.0, 0.0]
records:
  cloud: true
