name: arm
launch:
  - include:
      file: "$(find-pkg-share romea_arm_meta_bringup)/profile/urdf_broadcaster.py"
  - include:
      file: "$(find-pkg-share romea_arm_meta_bringup)/profile/ur.launch.py"
      arg:
        # - name: ip
        #   value: "1.1.1.1"
        - name: controller_configurations_file_path
          value: $(var controller_configurations_file_path)
configuration:
  manufacturer: ur
  model: "05"
  version: e
  home_joint_positions:
    shoulder_pan_joint: 0.0
    shoulder_lift_joint: -80.0
    elbow_joint: 155.0
    wrist_1_joint: 90.0
    wrist_2_joint: -90.0
    wrist_3_joint: 0.0
location:
  parent_link: "base_link"
  xyz: [2.02, 0.0, 0.54]
  rpy: [0.0, 0.0, 0.0]
records:
  joint_states: false
