x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      # TODO: adapt this path if you copy this config
      file: ${WORKSPACE}/docker/common.yaml
      service: x11_base
      # service: x11_gpu
    volumes:
      - ./config:/config
    environment:
      - CONFIG_DIR=/config
      - ROBOT_CONFIG_DIR=/config/adap2e
      # - ROBOT_CONFIG_DIR=/config/pom4x4
      - DEMO_MODE=simulation_gazebo
      - DEMO_NAME=simu_rosconfr
      - ROS_LOG_DIR=data/simu_rosconfr/log


services:
  simulator:
    <<: *base
    command: >-
      ros2 launch tirrex_core core.launch.py
        demo_configuration_directory:=$$CONFIG_DIR
        robot_configuration_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE

  bash:  # open a shell in the tirrex workspace
    <<: *base
    profiles: [optional]
    command: bash

  localisation:  # compute absolute localization using GNSS, IMU and odometry measurements
    <<: *base
    depends_on: [simulator]
    command: >-
      ros2 launch tirrex_core robot_localisation.launch.py
        demo_configuration_directory:=$$CONFIG_DIR
        robot_configuration_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE

  path_following:  # control the robot to follow the specified trajectory file
    <<: *base
    depends_on: [localisation]
    command: >-
      ros2 launch tirrex_core robot_path_following.launch.py
        demo_configuration_directory:=$$CONFIG_DIR
        robot_configuration_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        path:=weeding_v4.traj

  switcher:  # state machine to select robot control algorithm based on various events
    <<: [*base]
    depends_on: [path_following]
    command: >-
      ros2 launch romea_control_switcher switcher.launch.py
        config_file:=$$ROBOT_CONFIG_DIR/control_switcher.yaml
        mode:=$$DEMO_MODE

  path_recorder:  # record a trajectory file from the current localization
    <<: *base
    depends_on: [localisation]
    profiles: [optional]
    command: >-
      ros2 launch tirrex_core robot_path_recorder.launch.py
        demo_configuration_directory:=$$CONFIG_DIR
        robot_configuration_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        path:=$$CONFIG_DIR/paths/recorded.traj

  rviz:  # start evaluation nodes and publish information for rviz
    <<: *base
    command: rviz2 -d $$CONFIG_DIR/default.rviz

  record:
    <<: *base
    depends_on: [simulator]
    profiles: [optional]
    command: >-
      ros2 launch -d tirrex_core record.launch.py
        demo_configuration_directory:=$$CONFIG_DIR
        robot_configuration_directory:=$$ROBOT_CONFIG_DIR
        mode:=$$DEMO_MODE
        demo:=$$DEMO_NAME
